# Generated by Django 4.2.11 on 2026-04-07 23:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=10)),
                ('digito_verificador', models.CharField(max_length=1)),
                ('nombre_cliente', models.CharField(max_length=200)),
                ('ciudad', models.CharField(max_length=100)),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(max_length=20)),
                ('descuento_aplicado', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='Distribucion',
            fields=[
                ('id_distribucion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_distribucion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'distribucion',
            },
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id_insumo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_insumo', models.CharField(max_length=200)),
                ('unidad_control', models.CharField(max_length=20)),
                ('stock_sugerido_inicial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activo', models.CharField(default='S', max_length=1)),
            ],
            options={
                'db_table': 'insumo',
            },
        ),
        migrations.CreateModel(
            name='JornadaDiaria',
            fields=[
                ('id_jornada', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(unique=True)),
            ],
            options={
                'db_table': 'jornada_diaria',
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id_turno', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_turno', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'turno',
            },
        ),
        migrations.CreateModel(
            name='TipoProduccion',
            fields=[
                ('id_tipo_produccion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo_produccion', models.CharField(max_length=200)),
                ('id_insumo_principal', models.ForeignKey(db_column='id_insumo_principal', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.insumo')),
            ],
            options={
                'db_table': 'tipo_produccion',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=200)),
                ('precio_sugerido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_tipo_produccion', models.ForeignKey(db_column='id_tipo_produccion', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.tipoproduccion')),
            ],
            options={
                'db_table': 'producto',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pedido', models.DateField()),
                ('fecha_entrega_solicitada', models.DateField()),
                ('id_cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.CASCADE, to='api.cliente')),
                ('id_distribucion', models.ForeignKey(db_column='id_distribucion', on_delete=django.db.models.deletion.CASCADE, to='api.distribucion')),
            ],
            options={
                'db_table': 'pedido',
            },
        ),
        migrations.CreateModel(
            name='MovimientoBodega',
            fields=[
                ('id_movimiento_bodega', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_movimiento', models.DateField()),
                ('tipo_movimiento', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('AJUSTE', 'Ajuste')], max_length=10)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_insumo', models.ForeignKey(db_column='id_insumo', on_delete=django.db.models.deletion.CASCADE, to='api.insumo')),
                ('id_jornada', models.ForeignKey(blank=True, db_column='id_jornada', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.jornadadiaria')),
                ('id_turno', models.ForeignKey(blank=True, db_column='id_turno', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.turno')),
            ],
            options={
                'db_table': 'movimiento_bodega',
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id_detalle_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_solicitada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_cobrado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento_porcentaje_aplicado', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('id_pedido', models.ForeignKey(db_column='id_pedido', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='api.pedido')),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, to='api.producto')),
            ],
            options={
                'db_table': 'detalle_pedido',
            },
        ),
        migrations.CreateModel(
            name='DetalleMovimiento',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('precio_cobrado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento_porcentaje_aplicado', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('kilos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cancelacion', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.CASCADE, to='api.cliente')),
                ('id_distribucion', models.ForeignKey(db_column='id_distribucion', on_delete=django.db.models.deletion.CASCADE, to='api.distribucion')),
                ('id_jornada', models.ForeignKey(db_column='id_jornada', on_delete=django.db.models.deletion.CASCADE, to='api.jornadadiaria')),
                ('id_pedido', models.ForeignKey(blank=True, db_column='id_pedido', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.pedido')),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, to='api.producto')),
            ],
            options={
                'db_table': 'detalle_movimiento',
            },
        ),
        migrations.CreateModel(
            name='Produccion',
            fields=[
                ('id_produccion', models.AutoField(primary_key=True, serialize=False)),
                ('quintales', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_jornada', models.ForeignKey(db_column='id_jornada', on_delete=django.db.models.deletion.CASCADE, to='api.jornadadiaria')),
                ('id_tipo_produccion', models.ForeignKey(db_column='id_tipo_produccion', on_delete=django.db.models.deletion.CASCADE, to='api.tipoproduccion')),
                ('id_turno', models.ForeignKey(db_column='id_turno', on_delete=django.db.models.deletion.CASCADE, to='api.turno')),
            ],
            options={
                'db_table': 'produccion',
                'unique_together': {('id_jornada', 'id_tipo_produccion', 'id_turno')},
            },
        ),
        migrations.CreateModel(
            name='ConteoBodega',
            fields=[
                ('id_conteo_bodega', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_conteo', models.DateField()),
                ('cantidad_fisica', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('id_insumo', models.ForeignKey(db_column='id_insumo', on_delete=django.db.models.deletion.CASCADE, to='api.insumo')),
                ('id_turno', models.ForeignKey(blank=True, db_column='id_turno', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.turno')),
            ],
            options={
                'db_table': 'conteo_bodega',
                'unique_together': {('id_insumo', 'fecha_conteo', 'id_turno')},
            },
        ),
    ]
