# Generated by Django 4.2.11 on 2026-04-23 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_sincroniza_vistas_y_elimina_kilos'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallemovimiento',
            name='id_turno',
            field=models.ForeignKey(blank=True, db_column='id_turno', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.turno'),
        ),
        migrations.AddIndex(
            model_name='detallemovimiento',
            index=models.Index(fields=['id_turno'], name='idx_dm_turno'),
        ),
    ]
